export const 状态 = {
  功能总开关: true,
  功能开关: {},
  功能控制按钮: null,
  功能控制面板: null,
  原始战场节点快照: new WeakMap(),
  宽度: 0,
  高度: 0,
  塔列表: null,
  已知塔集合: new Set(),
  已知塔类型: new Map(),
  中立塔兵力表: new Map(),
  中立塔开塔成本表: new Map(),
  我方开塔增长表: new Map(),
  敌方推断开塔数: 0,
  敌方开塔确认集合: new Set(),
  已知基地集合: new Set(),
  已知敌方基地集合: new Map(),
  基地兵力表: new Map(),
  我方基地索引: null,
  基地被敌发现: false,
  基地被敌发现回合: null,
  基地危险背景豁免: false,
  已到达视野集合: new Set(),
  已确认视野集合: new Set(),
  已知障碍物集合: new Set(),
  不可达区域集合: new Set(),
  地图数组: null,
  原始兵力文本: new Map(),
  兵力分布着色列表: [],
  兵力分布调试: null,
  敌方移动高亮列表: [],
  敌方最强兵力位置: null,
  敌方基地接触列表: [],
  敌方基地候选列表: [],
  敌方基地推测调试: null,
  抢塔提示列表: [],
  敌方开塔提示: null,
  敌方开塔战场快照: null,
  敌方开塔调试: null,
  移动队列: [],
  自动保护基地接管: null,
  自动保护基地攻击序号: 1,
  自动吃基地接管: null,
  自动吃基地攻击序号: 1,
  我方行动类型表: new Map(),
  我方行动监控面板: null,
  帧数分布数据: {
    raf: [],
    耗时分布: [],
    样本数: 0,
    正在记录: false,
  },
  当前回合: null,
  大回合倒计时元素: null,
  上次大回合倒计时文本: '',
  战场数据已冻结: false,
  战场数据快照: null,
  战场塔信息快照: null,
  回放帧列表: [],
  回放当前帧索引: null,
  回放已结束: false,
  回放正在显示: false,
  回放已安装: false,
  回放元素: null,
  回放动画时间: null,
  我方索引: null,
  玩家名列表: null,
  队伍: null,
  已请求渲染: false,
  性能诊断: {
    地图更新: null,
    覆盖层渲染: null,
    页面观察: null,
    页面同步: null,
    socketHook: null,
    长任务: null,
  },
  自适应棋盘待同步: true,
  socket已挂钩: false,
  页面观察器: null,
  页面同步中: false,
  在主页面: true,
  战场表格缓存: null,
  已处理颜色数据包: new WeakSet(),
  原始兵力文本待渲染: false,
}

window.状态 = 状态
