export const 状态 = {
  宽度: 0,
  高度: 0,
  塔列表: null,
  已知塔集合: new Set(),
  已知塔类型: new Map(),
  中立塔兵力表: new Map(),
  已知基地集合: new Set(),
  已知敌方基地集合: new Map(),
  基地兵力表: new Map(),
  我方基地索引: null,
  基地被敌发现: false,
  已到达视野集合: new Set(),
  已知障碍物集合: new Set(),
  地图数组: null,
  原始兵力文本: new Map(),
  兵力分布着色列表: [],
  兵力分布调试: null,
  敌方移动高亮列表: [],
  抢塔提示列表: [],
  移动队列: [],
  自动吃基地接管: null,
  自动吃基地攻击序号: 1,
  空闲回合集合: new Set(),
  空闲回合操作集合: new Set(),
  空闲回合面板: null,
  当前回合: null,
  大回合倒计时元素: null,
  上次大回合倒计时文本: '',
  战场数据已冻结: false,
  战场数据快照: null,
  战场塔信息快照: null,
  结算回放快照: null,
  结算回放显示: false,
  结算回放已安装: false,
  我方索引: null,
  玩家名列表: null,
  队伍: null,
  已请求渲染: false,
  socket已挂钩: false,
  页面观察器: null,
  已处理颜色数据包: new WeakSet(),
  原始兵力文本待渲染: false,
}
